import type { CanonicalValue } from '@/lib/altvatar/types';

// The glyph whitelist: hand-reviewed names and labels beside the native value
// each draws. Seeded from the library's own already-human names, which is why
// most rows read identically — the review that matters is that every row was
// looked at, not that any row had to change.
export const GLYPHS: (CanonicalValue & { native: string })[] = [
  { value: 'alarm', label: 'Alarm', native: 'alarm' },
  { value: 'archive', label: 'Archive', native: 'archive' },
  { value: 'award', label: 'Award', native: 'award' },
  { value: 'bag', label: 'Bag', native: 'bag' },
  { value: 'bandaid', label: 'Bandaid', native: 'bandaid' },
  { value: 'bank', label: 'Bank', native: 'bank' },
  { value: 'basket', label: 'Basket', native: 'basket' },
  { value: 'basket-2', label: 'Basket 2', native: 'basket2' },
  { value: 'basket-3', label: 'Basket 3', native: 'basket3' },
  { value: 'bell', label: 'Bell', native: 'bell' },
  { value: 'bicycle', label: 'Bicycle', native: 'bicycle' },
  { value: 'binoculars', label: 'Binoculars', native: 'binoculars' },
  { value: 'book', label: 'Book', native: 'book' },
  { value: 'bookshelf', label: 'Bookshelf', native: 'bookshelf' },
  { value: 'boombox', label: 'Boombox', native: 'boombox' },
  { value: 'box-seam', label: 'Box Seam', native: 'boxSeam' },
  { value: 'box', label: 'Box', native: 'box' },
  { value: 'boxes', label: 'Boxes', native: 'boxes' },
  { value: 'bricks', label: 'Bricks', native: 'bricks' },
  { value: 'briefcase', label: 'Briefcase', native: 'briefcase' },
  {
    value: 'brightness-high',
    label: 'Brightness High',
    native: 'brightnessHigh',
  },
  { value: 'brush', label: 'Brush', native: 'brush' },
  { value: 'bucket', label: 'Bucket', native: 'bucket' },
  { value: 'bug', label: 'Bug', native: 'bug' },
  { value: 'building', label: 'Building', native: 'building' },
  { value: 'calculator', label: 'Calculator', native: 'calculator' },
  { value: 'camera-reels', label: 'Camera Reels', native: 'cameraReels' },
  { value: 'camera', label: 'Camera', native: 'camera' },
  { value: 'cart-2', label: 'Cart 2', native: 'cart2' },
  { value: 'cash-coin', label: 'Cash Coin', native: 'cashCoin' },
  { value: 'clock', label: 'Clock', native: 'clock' },
  { value: 'cloud-drizzle', label: 'Cloud Drizzle', native: 'cloudDrizzle' },
  { value: 'cloud-moon', label: 'Cloud Moon', native: 'cloudMoon' },
  { value: 'cloud-snow', label: 'Cloud Snow', native: 'cloudSnow' },
  { value: 'cloud', label: 'Cloud', native: 'cloud' },
  { value: 'clouds', label: 'Clouds', native: 'clouds' },
  { value: 'coin', label: 'Coin', native: 'coin' },
  { value: 'compass', label: 'Compass', native: 'compass' },
  { value: 'controller', label: 'Controller', native: 'controller' },
  { value: 'cup-straw', label: 'Cup Straw', native: 'cupStraw' },
  { value: 'cup', label: 'Cup', native: 'cup' },
  { value: 'dice-5', label: 'Dice 5', native: 'dice5' },
  { value: 'disc', label: 'Disc', native: 'disc' },
  { value: 'display', label: 'Display', native: 'display' },
  { value: 'door-closed', label: 'Door Closed', native: 'doorClosed' },
  { value: 'door-open', label: 'Door Open', native: 'doorOpen' },
  { value: 'dpad', label: 'Dpad', native: 'dpad' },
  { value: 'droplet', label: 'Droplet', native: 'droplet' },
  { value: 'easel', label: 'Easel', native: 'easel' },
  { value: 'egg-fried', label: 'Egg Fried', native: 'eggFried' },
  { value: 'egg', label: 'Egg', native: 'egg' },
  {
    value: 'emoji-heart-eyes',
    label: 'Emoji Heart Eyes',
    native: 'emojiHeartEyes',
  },
  { value: 'emoji-laughing', label: 'Emoji Laughing', native: 'emojiLaughing' },
  {
    value: 'emoji-smile-upside-down',
    label: 'Emoji Smile Upside Down',
    native: 'emojiSmileUpsideDown',
  },
  { value: 'emoji-smile', label: 'Emoji Smile', native: 'emojiSmile' },
  {
    value: 'emoji-sunglasses',
    label: 'Emoji Sunglasses',
    native: 'emojiSunglasses',
  },
  { value: 'emoji-wink', label: 'Emoji Wink', native: 'emojiWink' },
  { value: 'envelope', label: 'Envelope', native: 'envelope' },
  { value: 'eyeglasses', label: 'Eyeglasses', native: 'eyeglasses' },
  { value: 'flag', label: 'Flag', native: 'flag' },
  { value: 'flower-1', label: 'Flower 1', native: 'flower1' },
  { value: 'flower-2', label: 'Flower 2', native: 'flower2' },
  { value: 'flower-3', label: 'Flower 3', native: 'flower3' },
  { value: 'gem', label: 'Gem', native: 'gem' },
  { value: 'gift', label: 'Gift', native: 'gift' },
  { value: 'globe', label: 'Globe', native: 'globe' },
  { value: 'globe-2', label: 'Globe 2', native: 'globe2' },
  { value: 'hand-thumbs-up', label: 'Hand Thumbs Up', native: 'handThumbsUp' },
  { value: 'handbag', label: 'Handbag', native: 'handbag' },
  { value: 'hdd', label: 'Hdd', native: 'hdd' },
  { value: 'heart', label: 'Heart', native: 'heart' },
  {
    value: 'hourglass-split',
    label: 'Hourglass Split',
    native: 'hourglassSplit',
  },
  { value: 'hourglass', label: 'Hourglass', native: 'hourglass' },
  { value: 'house-door', label: 'House Door', native: 'houseDoor' },
  { value: 'house', label: 'House', native: 'house' },
  { value: 'inbox', label: 'Inbox', native: 'inbox' },
  { value: 'inboxes', label: 'Inboxes', native: 'inboxes' },
  { value: 'key', label: 'Key', native: 'key' },
  { value: 'keyboard', label: 'Keyboard', native: 'keyboard' },
  { value: 'ladder', label: 'Ladder', native: 'ladder' },
  { value: 'lamp', label: 'Lamp', native: 'lamp' },
  { value: 'laptop', label: 'Laptop', native: 'laptop' },
  { value: 'lightbulb', label: 'Lightbulb', native: 'lightbulb' },
  {
    value: 'lightning-charge',
    label: 'Lightning Charge',
    native: 'lightningCharge',
  },
  { value: 'lightning', label: 'Lightning', native: 'lightning' },
  { value: 'lock', label: 'Lock', native: 'lock' },
  { value: 'magic', label: 'Magic', native: 'magic' },
  { value: 'mailbox', label: 'Mailbox', native: 'mailbox' },
  { value: 'map', label: 'Map', native: 'map' },
  { value: 'megaphone', label: 'Megaphone', native: 'megaphone' },
  {
    value: 'minecart-loaded',
    label: 'Minecart Loaded',
    native: 'minecartLoaded',
  },
  { value: 'minecart', label: 'Minecart', native: 'minecart' },
  { value: 'moon-stars', label: 'Moon Stars', native: 'moonStars' },
  { value: 'moon', label: 'Moon', native: 'moon' },
  { value: 'mortarboard', label: 'Mortarboard', native: 'mortarboard' },
  { value: 'mouse', label: 'Mouse', native: 'mouse' },
  { value: 'mouse-2', label: 'Mouse 2', native: 'mouse2' },
  { value: 'newspaper', label: 'Newspaper', native: 'newspaper' },
  { value: 'paint-bucket', label: 'Paint Bucket', native: 'paintBucket' },
  { value: 'palette', label: 'Palette', native: 'palette' },
  { value: 'palette-2', label: 'Palette 2', native: 'palette2' },
  { value: 'paperclip', label: 'Paperclip', native: 'paperclip' },
  { value: 'pen', label: 'Pen', native: 'pen' },
  { value: 'pencil', label: 'Pencil', native: 'pencil' },
  { value: 'phone', label: 'Phone', native: 'phone' },
  { value: 'piggy-bank', label: 'Piggy Bank', native: 'piggyBank' },
  { value: 'pin-angle', label: 'Pin Angle', native: 'pinAngle' },
  { value: 'plug', label: 'Plug', native: 'plug' },
  { value: 'printer', label: 'Printer', native: 'printer' },
  { value: 'projector', label: 'Projector', native: 'projector' },
  { value: 'puzzle', label: 'Puzzle', native: 'puzzle' },
  { value: 'router', label: 'Router', native: 'router' },
  { value: 'scissors', label: 'Scissors', native: 'scissors' },
  { value: 'sd-card', label: 'Sd Card', native: 'sdCard' },
  { value: 'search', label: 'Search', native: 'search' },
  { value: 'send', label: 'Send', native: 'send' },
  { value: 'shop-window', label: 'Shop Window', native: 'shopWindow' },
  { value: 'shop', label: 'Shop', native: 'shop' },
  { value: 'signpost-2', label: 'Signpost 2', native: 'signpost2' },
  { value: 'signpost-split', label: 'Signpost Split', native: 'signpostSplit' },
  { value: 'signpost', label: 'Signpost', native: 'signpost' },
  { value: 'smartwatch', label: 'Smartwatch', native: 'smartwatch' },
  { value: 'snow', label: 'Snow', native: 'snow' },
  { value: 'snow-2', label: 'Snow 2', native: 'snow2' },
  { value: 'snow-3', label: 'Snow 3', native: 'snow3' },
  { value: 'speaker', label: 'Speaker', native: 'speaker' },
  { value: 'star', label: 'Star', native: 'star' },
  { value: 'stoplights', label: 'Stoplights', native: 'stoplights' },
  { value: 'stopwatch', label: 'Stopwatch', native: 'stopwatch' },
  { value: 'sun', label: 'Sun', native: 'sun' },
  { value: 'tablet', label: 'Tablet', native: 'tablet' },
  { value: 'thermometer', label: 'Thermometer', native: 'thermometer' },
  {
    value: 'ticket-perforated',
    label: 'Ticket Perforated',
    native: 'ticketPerforated',
  },
  { value: 'tornado', label: 'Tornado', native: 'tornado' },
  { value: 'trash', label: 'Trash', native: 'trash' },
  { value: 'trash-2', label: 'Trash 2', native: 'trash2' },
  { value: 'tree', label: 'Tree', native: 'tree' },
  { value: 'trophy', label: 'Trophy', native: 'trophy' },
  { value: 'truck-flatbed', label: 'Truck Flatbed', native: 'truckFlatbed' },
  { value: 'truck', label: 'Truck', native: 'truck' },
  { value: 'tsunami', label: 'Tsunami', native: 'tsunami' },
  { value: 'umbrella', label: 'Umbrella', native: 'umbrella' },
  { value: 'wallet', label: 'Wallet', native: 'wallet' },
  { value: 'wallet-2', label: 'Wallet 2', native: 'wallet2' },
  { value: 'watch', label: 'Watch', native: 'watch' },
  { value: 'webcam', label: 'Webcam', native: 'webcam' },
];
