import { DEFAULT_GLYPH } from '@/lib/altvatar/styles/openmoji';
import entries from '@/lib/altvatar/openmoji.catalog.json';

// Generated by scripts/build-openmoji.mjs rather than hand-authored: the
// canonical-vocabulary rule exists so a selection survives a style change, and
// the thing kind has no sibling style to carry a value to. Curation lives in
// that script so nothing here holds the package's 2.2MB metadata open.

export type OpenmojiEntry = { code: string; label: string };

const ROWS = entries as [code: string, label: string, search: string][];

export const OPENMOJI_CATALOG: OpenmojiEntry[] = ROWS.map(([code, label]) => ({
  code,
  label,
}));

const searchable = new Map(ROWS.map(([code, , search]) => [code, search]));

// The trust boundary for a stored `glyph`: a code outside the set — malformed,
// excluded, or retired — falls back rather than reaching the filesystem.
export const safeOpenmojiCode = (code: string | undefined): string =>
  code !== undefined && searchable.has(code) ? code : DEFAULT_GLYPH;

// An empty query returns the catalog itself, so the surface opens populated
// rather than blank.
export function searchOpenmoji(
  query: string,
  limit = 60,
  offset = 0
): { entries: OpenmojiEntry[]; hasMore: boolean } {
  const q = query.trim().toLowerCase();
  const hits =
    q === ''
      ? OPENMOJI_CATALOG
      : OPENMOJI_CATALOG.filter((e) => searchable.get(e.code)!.includes(q));
  return {
    entries: hits.slice(offset, offset + limit),
    hasMore: hits.length > offset + limit,
  };
}
