import { initialsOf } from './utils';
import '@/app/ui/styles/altvatar-disc.css';
import { accentVars } from '@/lib/accent';
import { styleOf } from '@/lib/altvatar/registry';
import type { ProfileAvatarView } from '@/lib/types';

// A name with no profile behind it: a free-text purchaser, or an account whose
// active profile has not resolved. Initials on the unset disc, which is a state
// the disc already draws — not a fourth branch.
export const facelessView = (
  name: string | null | undefined
): ProfileAvatarView => ({
  name: name ?? '',
  accent: null,
  art: null,
  avatarStyle: null,
});

// The one avatar disc in the app. It paints the accent's light stop, then
// fills: the profile's Altvatar art where it has any, its initials otherwise.
// There is no third leg — a profile's name is required, so initials always
// resolve — and no branch on whether an account backs the profile.
export default function ProfileAvatar({
  profile,
  className,
}: {
  profile: ProfileAvatarView;
  className?: string;
}) {
  const { art, avatarStyle, name, accent } = profile;
  // A glyph style generates flat alpha with no colour of its own, so the disc
  // paints it from the accent's ink through a mask. Baking the ink into the
  // SVG instead would couple every future accent write to a regeneration.
  const isGlyph = art && avatarStyle ? !!styleOf(avatarStyle).glyph : false;

  return (
    <span
      className={`altvatar-disc${className ? ` ${className}` : ''}`}
      style={accentVars(accent)}
      aria-hidden
    >
      {art && isGlyph && (
        <span
          className="altvatar-disc-glyph"
          data-testid="altvatar-glyph"
          style={{
            maskImage: `url("${art}")`,
            WebkitMaskImage: `url("${art}")`,
          }}
        />
      )}
      {art && !isGlyph && (
        // Plain <img> rather than next/image: the source is a self-contained
        // data URI generated by this app, so there is no remote origin for the
        // optimizer to fetch, resize or whitelist.
        // eslint-disable-next-line @next/next/no-img-element -- data URI, see above
        <img
          src={art}
          alt=""
          className="altvatar-disc-art"
          data-testid="altvatar-art"
        />
      )}
      {!art && (
        <span className="altvatar-disc-initials">{initialsOf(name)}</span>
      )}
    </span>
  );
}
